### ISSUE TITLE
MSF - Goma: Multiple patients under ARV + TB treatment

### ISSUE THREAD

**Issue by Fatoufall** [medic/config-msf#131]
With one phone holder, created 4 patients:
- 2 under ARV and TB
- 1 women with TB only, delivery expected July 11th
- 1 pregnant women without TB, delivery expected July 9th

<img width="1188" alt="Capture d’écran 2020-07-09 à 13 34 31" src="https://user-images.githubusercontent.com/35699783/87047550-30980a80-c1ea-11ea-9bc6-66d07a57edc1.png">

**General follow up:** 
- the reason is displayed in english (see screenshot)
- Avez-vous un "developpement" à signaler par rapport au patient? @boussokane to check this translation, should be changement for example

**ARV treatment issue**
- icon not consistent (see screenshot)
- no SMS or task for Forgot treatment (not implemented)
- received SMS in english: Does "patient" have at least 2 weeks of ARV treatment....

**No response**
Not implemented in french as action

**Title when re-schedule a task**
When submitted lab assessment or a TB treatment follow up by selecting If response=“No remind again tomorrow” to trigger the same task after 24 hours 
Expected results: title should be displayed well as previously

Current results:
<img width="1147" alt="Capture d’écran 2020-07-10 à 16 15 20" src="https://user-images.githubusercontent.com/35699783/87069381-9e522f80-c206-11ea-8353-daad2fe9c3d9.png">

**Comment by Fatoufall** [comment]
- forgot treatment implemented but I received SMS every 30 min even if I already responded for the same patient.

**Comment by kitsao** [comment]
#### General follow up:

- [ ] the reason is displayed in english (see screenshot)
- [ ] Avez-vous un "developpement" à signaler par rapport au patient? @boussokane to check this translation, should be changement for example

#### ARV treatment issue

- [ ] icon not consistent (see screenshot)
- [ ] no SMS or task for Forgot treatment (not implemented)
- [ ] received SMS in english: Does "patient" have at least 2 weeks of ARV treatment....

#### No response
- [ ] Not implemented in french as action

#### Title when re-schedule a task
- [ ] When submitted lab assessment or a TB treatment follow up by selecting If response=“No remind again tomorrow” to trigger the same task after 24 hours
- [ ] Expected results: title should be displayed well as previously

**Comment by Fatoufall** [comment]
- [ ] end  message not received for new patient (even for existing patients). As a result, received every 30 min message "forgot treatment" SMS and even if I respond the SMS is sent over and over
