### ISSUE TITLE
Investigate how we can force user to disconnect from the app in order to clear data first and log in again.

### ISSUE THREAD

**Issue by senseibara** [medic/config-msf#76]
few ideas : 
- Change every users passwords 
- Moving the app to a sub-domain

**Comment by kennsippell** [comment]
For the MSF-Niger project, we are in the process of updating the project's hierarchy to add regional-level response centres.  Users for this project use a web browser and do not use an Android App. As a result of this change, we are asking every user to

1. Sync their data EOD Friday
1. Clear their cache
1. Go home for the night
1. Wake up in the morning and re-sync all data
1. Resume work

MSF has expressed concerns that they won't be able to coordinate cache clearing across all their users.  How can we force users to disconnect from the app and do an inital replication here?  One thing I'm considering is moving the project to a different subdomain, and setting up their old subdomain to hard-redirect to the new? (I'm not sure if this would even work due to service-worker cache).

I'm looking for ideas to help ease the operational burdens.
